version: "3.3"
services:
  core:
    build: .
    ports:
      - "5000:5000"
      - "2222:2222"
      # Bind Mount the current working directory into the container as /shruti
    volumes:
      - ../shruti:/shruti
